name: JD_speed

on:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: 'run 天天加速' 
        run: python3 JD_speed.py 
        env:
            JD_COOKIE: ${{ secrets.JD_COOKIE }}
            SCKEY: ${{ secrets.SCKEY }}
     
    
